import {parseEther} from "ethers";

export const OPEN_STORE_ERRORS = {
    VERSION_CONFIG_MUST_INCREASE: 1,
    VALIDATOR_UNSUPPORTED_VERSION: 2,
    VALIDATOR_ALREADY_REGISTERED: 3,
    INSUFFICIENT_STAKE: 4,
    VALIDATOR_NOT_REGISTERED: 5,
    VALIDATOR_IN_QUEUE: 6,
    VALIDATOR_IN_EMERGENCY_LOCK: 7,
    QUEUE_SUSPENDED: 8,
    VALIDATOR_ALREADY_IN_QUEUE: 9,
    BLOCK_ID_NOT_INCREMENTAL: 10,
    INSUFFICIENT_BALANCE_FOR_PROPOSAL: 11,
    INSUFFICIENT_VOTING_BALANCE: 12,
    CANNOT_UNASSIGN_BLOCK: 13,
    INSUFFICIENT_BALANCE: 14,
    REQUESTS_SUSPENDED: 15,
    INCORRECT_VALIDATION_FEE: 16,
    NOT_TARGET_OWNER: 17,
    BUILD_ALREADY_VERIFIED: 18,
    OWNER_NOT_VERIFIED: 19,
    BLOCK_ID_NOT_NEXT_TO_FINALIZE: 20,
    INVALID_REQUEST_ID_RANGE: 21,
    TOO_MANY_REQUESTS_IN_BLOCK: 22,
    SENDER_NOT_BLOCK_OWNER: 23,
    INVALID_TO_REQUEST_ID: 24,
    INVALID_FROM_REQUEST_ID: 25,
    PROPOSAL_ALREADY_EXISTS: 26,
    NO_PROPOSAL_TO_DISCUSS: 27,
    DISCUSSION_FROM_REQ_ID_MISMATCH: 28,
    DISCUSSION_TO_REQ_ID_MISMATCH: 29,
    CANNOT_DISCUSS_AFTER_VOTE: 30,
    MAX_PARALLEL_PROPOSALS_REACHED: 31,
    BLOCK_ID_NOT_NEXT_TO_PROPOSE: 32,
    VOTER_NOT_REGISTERED: 33,
    CANNOT_VOTE_FOR_SELF: 34,
    PROPOSAL_NOT_FOUND: 35,
    VOTING_PERIOD_CLOSED: 36,
    INSUFFICIENT_BALANCE_FOR_VOTE: 37,
    ALREADY_VOTED: 38,
    PROPOSAL_NOT_READY_TO_FINALIZE: 39,
    INVALID_TRACK_ID: 40,
    BUILD_VERSION_DOWNGRADED: 41,
    BUILD_VERSION_ZERO: 42,
    DISCUSSION_RESULT_SAME: 43,
    UNKNOWN_REQUEST_TYPE: 43,
};

export const BLOCK_RESULT_STATUS = {
    UNAVAILABLE: 0,  // 00
    SUCCESS: 1,      // 01
    RESERVED: 2,     // 10
    ERROR: 3,        // 11
};

export const BLOCK_MASK = {
    IS_DISCUSSION: 1,
};
